bitmap: assets/map_inputs/room.png

pattern_size: 3
map_width: 10
map_height: 10

tile_data:
  0:
    name: tan
    texture: beach.png
    bitColor: [238, 195, 154, 255]

  1:
    name: green
    texture: grass.png
    bitColor: [106, 190, 48, 255]

  2:
    name: teal
    texture: water.png
    bitColor: [95, 205, 228, 255]

  3:
    name: forrest
    texture: forrest.png
    bitColor: [75, 105, 47, 255]

  4:
    name: orange
    texture: desert.png
    bitColor: [223, 113, 38, 255]
    