screen_width: 600
screen_heigh: 800

map_width: 30
map_height: 30

tile_data:
  0:
    name: water
    texture: water.png
  1:
    name: beach
    texture: beach.png
  2:
    name: forrest
    texture: forrest.png
  3:
    name: grass
    texture: grass.png
  4:
    name: desert
    texture: desert.png
  5:
    name: mountains
    texture: mountains.png

valid_neighbors:
  water: [water, beach]    
  beach: [water, beach, grass]
  forrest: [grass, forrest, mountains]
  grass: [forrest, grass, beach]
  desert: [mountains, desert]
  mountains: [forrest, desert, mountains]